FROM ghcr.io/epics-containers/ioc-generic-developer:2025.4.2b1

# Optional: Set working directory
WORKDIR /epics

# Start caRepeater as the container CMD
CMD ["/epics/epics-base/bin/linux-x86_64/caRepeater"]
