services:
  solar_ioc:
    build: ./solar_ioc
    container_name: solar_ioc
    hostname: solar_ioc
    networks:
      - epics-net

  battery_ioc:
    build: ./battery_ioc
    container_name: battery_ioc
    hostname: battery_ioc
    networks:
      - epics-net

  wind_ioc:
    build: ./wind_ioc
    container_name: wind_ioc
    hostname: wind_ioc
    networks:
      - epics-net

  pysim:
    build: ./pysim
    container_name: pysim
    hostname: pysim
    networks:
      - epics-net

  client:
    image: ghcr.io/epics-containers/ioc-generic-developer:2025.4.2b1
    container_name: client
    stdin_open: true
    tty: true
    networks:
      - epics-net
    environment:
      - EPICS_CA_AUTO_ADDR_LIST=NO
      - EPICS_CA_ADDR_LIST=ioc1

  phoebus:
    build: ./phoebus
    container_name: phoebus
    hostname: phoebus
    networks:
      - epics-net
    command: sleep infinity # Keep the container running
    environment:
      - DISPLAY
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
    volumes:
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true

networks:
  epics-net:
